.\" Process this file with
.\" groff -man -Tascii bashrun.1
.\"
.TH BASHRUN 1 "2010-05-22" "Linux" "User manuals"
.SH NAME
\fBbashrun\fP \- launch applications from interactive bash sessions
.SH SYNOPSIS
\fBbashrun\fP [\fIoption\fP] [\fIcommand\fP [\fIarg...\fP]] [-- \fItermopt...\fP]
.SH DESCRIPTION
.PP
\fBbashrun\fP provides application launching and terminal window
management capabilities to interactive bash sessions, suitable for use
in a graphical user environment.

In its default setup, \fBbashrun\fP creates an interactive bash
session running in a small \fBxterm\fP(1) terminal window, thus
providing a simple run dialog (\fIlauncher\fP mode). It can also be
used from a regular terminal session, allowing the user to seamlessly
launch both graphical and terminal applications from the command line
(using \fIterminal\fP mode or the \fBREMOTE CONTROL INTERFACE\fP).
.SH OVERVIEW
Bashrun is composed out of a set of user configurable \fBobjects\fP
that control different aspects of application launching and terminal
management:

\fBModes\fP control the appearance and behavior of the terminal
hosting the bashrun session, such as the default modes \fIlauncher\fP
and \fIterminal\fP described above.

\fBActions\fP can be bound to key sequences and handle user input in
different ways, such as launching a command in a terminal or looking
up words in a dictionary client.

\fBTerminals\fP allow the user to specify different terminal command
lines to be used for launching console applications, and can be
associated with specific commands or command lines.

\fBRules\fP associate \fBactions\fP with specific commands or command
lines, e.g. to automatically launch certain commands in a
\fBterminal\fP. Regular expressions allow fine grained control over
command matching.

\fPHandlers\fP provide a flexible mechanism for rewriting
non-executable commands, using regular expression matching,
substitution and file test operators, thus offering a way to implement
stuff like file associations or web shortcuts. They also provide a
simple interface to programmable completion.

\fBPlugins\fP allow flexible inclusion and distribution of user
created configuration objects.
.SH COMMAND LINE INTERFACE
The \fBbashrun\fP executable provides a command line interface to
bashrun sessions and can be used to create, select and control bashrun
sessions running in different \fBmodes\fP. It can manage a single
bashrun session for each \fBmode\fP object defined in the
configuration file.

Modes are selected by the \fB-m\fP or \fB\--mode\fP option. If no
\fBmode\fP is specified, the default \fBmode\fP \fIlauncher\fP is
used.

If no session is currently running in the selected \fBmode\fP, then a
session is started in the selected \fBmode\fP. The \fBcommand\fP, if
given, is then applied to the newly created session, unless the
\fBcommand\fP is either \fIexit\fP, \fIwid\fP or \fIpid\fP. If no
\fBcommand\fP is specified, the default \fBcommand\fP \fIshow\fP is
used.
.SS OPTIONS
.IP \fB-m\fP,\ \fB--mode\fP\ \fImode\fP
Select mode to launch or control. In the absence
of this option, the default mode \fIlauncher\fP is used.
.IP \fB--remote-control\fP
Print bash code to create a remote control interface to an existing bashrun
session on stdout. See \fBREMOTE CONTROL INTERFACE\fP.
.IP \fB-d\fP,\ \fB--debug\fP
Enable debugging on startup
.IP \fB-h\fP,\ \fB--help\fP
Show usage information
.IP \fB-v\fP,\ \fB--version\fP
Show version information
.SS COMMANDS 
.IP \fBshow\fP
Show the terminal window. Maps the window, moves it to the current
desktop, moves it above other windows and focuses it. This is the
default command if no command has been specified.
.IP \fBhide\fP
Unmap the terminal window.
.IP \fBtoggle\fP
If the terminal window is not mapped, \fBshow\fP it. If the terminal window
is mapped, \fBhide\fP it.
.IP \fBsmart\fP
If the terminal window is not mapped, not on the current desktop,
obscured by other windows or not focused, then \fBshow\fP it. If none
of these conditions apply, \fBhide\fP the terminal window.
.IP \fBdo\fP\ \fIaction\fP\ [\fIshell-command\fP]
Remotely invoke \fIaction\fP with
\fIshell-command\fP. If the requested action involves
.BR su (1),
the terminal window is shown before invoking the action to allow
password entry.
.IP \fBsu\fP\ \fIshell-command\fP
Remotely invoke the \fIsu-run\fP action with \fIshell-command\fP. This is
the equivalent to \fBdo\fP \fIsu-run\fP \fIshell-command\fP.
.IP \fBwid\fP
Report the window id of the terminal window.
.IP \fBpid\fP
Report the process id of the bash session.
.IP \fBdebug\fP
Toggle debugging.
.IP \fBreload\fP
Reload configuration files.
.IP \fBrestart\fP
Exit the bashrun session and start a new one.
.IP \fBexit\fP
Exit the bashrun session.
.SH CONFIGURATION 
.SH BUGS
Please report any bugs you may find using the email address
below. Comments, suggestions, feedback of any kind is appreciated.
.SH AUTHOR
Henning Bekel <h.bekel at googlemail dot com> (english and german)
.SH "SEE ALSO"
.BR bash (1)
.BR readline (3)
.BR xterm (1)
.BR su (1)
.BR stty (1)

\" Handler setup:
\"   1. Reorder handlers     
\"     If --fallback is true, move handlers to the end of the chain.
\"     Fallback handlers will end up at the end of the chain in the
\"     order they are defined in this configuration file.    
\"   2. Setup completion    
\"     If --complete is given, create a stub function using the
\"     word given as the function name, so that the word can be
\"     completed to from an empty commandline.    
\"       If a function by the name +handler-<handlername>-complete
\"       is defined, install a completion function for the word
\"       given in --complete that uses the output of the supplied
\"       function to dynamically retrieve a list of words to
\"       complete against.  
\"       If no such function is defined, install default completion
\"       for the word given in --complete.
\" Handler processing: 
\"   Match the line against the regular expression in --pattern
\"     Perform one or more optional tests using the 'test' builtin.
\"     A string of test characters, corresponding to the option
\"     characters of the options to the test builtin, can be given
\"     in --test. Prefixing a test character with '!' negates the
\"     test.  Tests are performed in the order in which they appear
\"     in --test. If one of these tests fails, testing is aborted
\"     and the test as a whole fails.
\"       Rewrite the string depending on its contents:       
\"         If the string contains back references (%[0-9]), replace
\"         them with the string matching the corresponding
\"         subpatterns
\"         If the string contains no back references, append the
\"         line to the string, separating them with a space
\"         character.
\"     If an --action has been specified, run the action on the
\"     resulting string
\"     If no --action has been specified, assume that the string now
\"     constitutes an executable commandline, and launch it in the
\"     background, detached from the bashrun shell.
    

