=pod
=head1 SYNOPSIS
bashrun [option] [command] [args] 
=head1 DESCRIPTION
bashrun is an application launcher for X11. It runs an interactive bash
session in a small terminal window, providing all the common bash
features like readline line editing, aliases, tab completion and
history, while adding more features like bookmarks, regexp based
handlers, dictionary lookups and google search queries.

=head1 OPTIONS
=head1 COMMANDS
=head1 ARGUMENTS
=head1 INVOCATION
