#!/bin/bash
BASHRUN_PREFIX=`which bashrun 2> /dev/null`
BASHRUN_PREFIX=${BASHRUN_PREFIX/\/bin\/bashrun/}
BASHRUN_SHARE="$BASHRUN_PREFIX/share/bashrun-engine"

. $BASHRUN_SHARE/frontend

if [ -f "$BASHRUN_REGISTRY" ]; then    
    
    # get window id and current mode of the oldest instance
    [[ "$(cat $BASHRUN_REGISTRY | head -1)" =~ ([0-9]+):(.+) ]]
    
    wid="${BASH_REMATCH[1]}"
    mode="${BASH_REMATCH[2]}"
    
    # set window id and mode
    bashrun.window.id "$wid"
    modes.seek "$mode"

    bashrun.window.toggle
else
    # startup mode defaults to launcher
    mode="${1:-launcher}"
    
    # get the bashrun terminal
    terminals.seek "bashrun"

    # get requested mode
    if ! modes.seek "$mode"; then
	echo "$0: warning: no such mode '$mode', using 'launcher'" 
	mode="launcher"
	modes.seek $mode
    fi

    # get command and insert properties and geometry from requested mode
    command="$(terminal.get_command)"
    command=${command//%m/$mode}
    command=${command//%g/$(mode.get_geom | cut -d ' ' -f 1)}
    
    echo "BASHRUN=1 BASHRUN_MODE=\"$mode\" $command &"

    BASHRUN=1 BASHRUN_MODE="$mode" $command &
fi
