# -*- shell-script -*-

################################################################################
#
# Load and initialize the bashrun engine.
# This file needs to be sourced from ~/.bashrc if BASHRUN=1
#
################################################################################

# never source bashrun from console
if [[ "$TERM" == "linux" ]]; then    
    return 1
fi
# bootstrap install locations
path=$(type -p bashrun 2>/dev/null) 
prefix=${path/\/bin\/bashrun/}

# source global variables
source $prefix/share/bashrun/globals
unset path prefix

# initialize object system
source $BASHRUN_SHARE/objects
§objects.site $BASHRUN_SHARE
§objects.cache_home $BASHRUN_CACHE_HOME
§objects.data_home $BASHRUN_CACHE_HOME
§objects.namespace "bashrun"

# source utilities 
source $BASHRUN_SHARE/utils
source $BASHRUN_SHARE/window
source $BASHRUN_SHARE/registry
source $BASHRUN_SHARE/xdotool
source $BASHRUN_SHARE/message
source $BASHRUN_SHARE/bootstrap

# register this instance (needs to happen early on)
# unless we're not launched by the frontend...
[[ BASHRUN_FRONTEND -eq 1 ]] && §registry.add

# setup progress bar
source $BASHRUN_SHARE/progress
§progress.new "Initializing... [objects]"

# continue sourcing utilities
source $BASHRUN_SHARE/config
source $BASHRUN_SHARE/plugin
source $BASHRUN_SHARE/remote
source $BASHRUN_SHARE/geometry
source $BASHRUN_SHARE/command
source $BASHRUN_SHARE/readline
source $BASHRUN_SHARE/completion

# source objects
source $BASHRUN_SHARE/modes
source $BASHRUN_SHARE/terminals
source $BASHRUN_SHARE/actions
source $BASHRUN_SHARE/bindings
source $BASHRUN_SHARE/handlers
source $BASHRUN_SHARE/rules
source $BASHRUN_SHARE/bookmarks

# source and initialize the engine
source $BASHRUN_SHARE/engine
§engine.init
